### ISSUE TITLE
Error in Main.py

### ISSUE THREAD

**Issue by dhuadaar** [tjwei/Quick-Neural-Art-Transfer#2]
The main.py when run throws an Attribute error. This is because class objects are being initialized using data of three different folders out of which "~./Output/ " is missing.

I get the following error from the prompt.

```
C:\Users\user\Documents\GitHub\Quick-Neural-Art-Transfer [master +0 ~1 -0]>
C:\Users\user\Documents\GitHub\Quick-Neural-Art-Transfer [master +0 ~1 -0]> python main.py
[INFO              ] [Logger      ] Record log in C:\Users\user\.kivy\logs\kivy_16-03-13_7.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <4.2.0 - Build 10.18.10.3379>
[INFO              ] [GL          ] OpenGL vendor <Intel>
[INFO              ] [GL          ] OpenGL renderer <Intel(R) HD Graphics 4400>
[INFO              ] [GL          ] OpenGL parsed version: 4, 2
[INFO              ] [GL          ] Shading version <4.20 - Build 10.18.10.3379>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
content/tjw2.jpg
1227
(1227L, 1443L, 3L)
(dtype('uint8'), dtype('float64'))
output/tjw_a.png
 Traceback (most recent call last):
   File "main.py", line 73, in <module>
     ("content/smile_face.jpg", "styles/gh.jpg", "output/c5.png")]]
   File "main.py", line 55, in __init__
     self.output = get_img(output)
   File "main.py", line 47, in get_img
     print len(img)
 TypeError: object of type 'NoneType' has no len()
C:\Users\user\Documents\GitHub\Quick-Neural-Art-Transfer [master +0 ~1 -0]>
```

**Comment by dhuadaar** [comment]
Sorry, there is a small mistake.

I wrote a line of code

```
print len(img)
```

for my own convenience and it throws TypeError. But when the line is deleted the next line which is supposed to print the img shape throws an AttributError as None img as no attribute shape.

**Comment by tjwei** [comment]
output files have added 
https://github.com/tjwei/Quick-Neural-Art-Transfer/commit/721c657cbf7f7d78a37bba66efb5e5c23cc05551
