### ISSUE TITLE
NameError: global name 'kweargs' is not defined

### ISSUE THREAD

**Issue by albertyou2** [tjwei/Quick-Neural-Art-Transfer#4]
hi @tjwei 
I followed the instructions and finished the installation .
Then I run “python nstest.py”  and get an error:
Traceback (most recent call last):
  File "nstest.py", line 2, in <module>
    import neuralStyle
  File "/home/sojoyoo/neural_style_kivy/neuralStyle.py", line 69, in <module>
    net = build_model()
  File "/home/sojoyoo/neural_style_kivy/neuralStyle.py", line 44, in build_model
    net['conv1_1'] = ConvLayer(net['input'], 64, 3, pad=1)
  File "/home/sojoyoo/neural_style_kivy/neuralStyle.py", line 35, in ConvLayer
    return ConvLayer0(*args, flip_filters=False, **kweargs)
NameError: global name 'kweargs' is not defined

Do you know how to solve this ?
Thank you

**Comment by tjwei** [comment]
Thanks. It is a typo, kweargs should be kwargs. The latest commit should fix it.

**Comment by albertyou2** [comment]
ok,i'll try it
